language: node_js
node_js:
  - "7"

before_install: 
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8

install:
  - npm ci

script:
  - npm run-script build
  - npm test

after_success: 
  - npm test
