language: node_js
node_js:
  - "11"

before_install: 
  - dpkg --compare-versions `npm -v` ge 6.4 || npm i -g npm@^6.4

install:
  - yarn ci

script:
  - npm run-script build
  - npm test

after_success: 
  # - npm test
