language: node_js
node_js:
  - "7"

before_install: 
  - dpkg --compare-versions `npm -v` ge 6.4 || npm i -g npm@^6.4
  - node --version

install:
  - npm ci

script:
  - npm run-script build
  - npm test

after_success: 
  # - npm test
